baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'creme caramel'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Blogs'
    pageRef = '/blog'
    weight = 12

  [[menus.main]]
    name = 'Projects'
    pageRef = '/project'
    weight = 14

  [[menus.main]]
    name = 'Guides'
    pageRef = '/guide'
    weight = 16

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
